apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-v2
spec:
  selector:
    matchLabels:
      app: frontend-v2
  template:
    metadata:
      labels:
        app: frontend-v2
    spec:
      containers:
      - name: frontend-v2
        image: nurhun/django_rest_framework_movies_apis_w_react_frontend_nginx:v0.2.0
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-v2
spec:
  selector:
    app: frontend-v2
  ports:
  - port: 80
    targetPort: 80

